Repository AJOU-DEVELOPERS/Do-IT-Page, pull requests merged in 2022-03, with the labels that each got.

#65 [ FE ] 메인 페이지 반응형 디자인(Phone) 및 메뉴 토글 애니메이션 추가
  Client/package-lock.json
  Client/package.json
  Client/src/Components/Atoms/ContentImg/styles.tsx
  Client/src/Components/Atoms/ContentText/styles.tsx
  Client/src/Components/Atoms/StyledLink/index.tsx
  Client/src/Components/Molecules/Board/BoardPreview/Basic/style.tsx
  Client/src/Components/Molecules/Common/Header/style.tsx
  Client/src/Components/Molecules/Content/ContentTitle/style.tsx
  Client/src/Components/Organisms/Common/Calendar/style.tsx
  Client/src/Components/Organisms/Common/Footer/style.tsx
  Client/src/Components/Organisms/Common/Header/styles.tsx
  Client/src/Components/Organisms/Main/BoardContent/style.tsx
  Client/src/Components/Organisms/Reserve/ReserveCalendar/Body/styles.tsx
  Client/src/Components/Templates/Main/style.tsx
Labels: FE, Feat, CSS

#67 [ FE ] 과방 대여 페이지 반응형 디자인 (Phone)
  Client/src/Components/Atoms/Input/styles.tsx
  Client/src/Components/Molecules/ReserveForm/index.tsx
  Client/src/Components/Molecules/ReserveForm/style.tsx
  Client/src/Components/Organisms/BoardBody/styles.tsx
  Client/src/Components/Organisms/Reserve/Body/styles.tsx
  Client/src/Components/Organisms/Reserve/ReserveBox/index.tsx
  Client/src/Components/Organisms/Reserve/ReserveBox/styles.tsx
  Client/src/Components/Organisms/Reserve/ReserveCalendar/styles.tsx
Labels: FE, Feat, CSS

#74 [ FE ] Feat Login Feature
  Client/public/dummyData/checkLogIn.json
  Client/src/API/Account/index.ts
  Client/src/API/index.ts
  Client/src/Common/Type/Account/index.ts
  Client/src/Components/Molecules/Account/LoginInput.tsx
  Client/src/Components/Molecules/Account/util.ts
  Client/src/Components/Molecules/Admin/SubSection/Work/util.ts
  Client/src/Components/Molecules/Content/studyProject.tsx
  Client/src/Components/Molecules/Content/util.tsx
  Client/src/Components/Organisms/Common/Header/index.tsx
  Client/src/Recoil/CheckLogin/index.tsx
  Client/src/Routes/PrivateRoute.tsx
  Client/src/Routes/PublicRoute.tsx
Labels: FE, Feat, Fix, Refactor

#80 [BE] API 추가, 응답 dto 리펙토링
  Server/src/app.module.ts
  Server/src/auths/auth.jwt.guard.ts
  Server/src/auths/auth.jwt.strategy.ts
  Server/src/auths/auth.local.strategy.ts
  Server/src/auths/auth.service.ts
  Server/src/auths/dto/mail-auth.dto.ts
  Server/src/commons/dto/response-common.dto.ts
  Server/src/departments/departments.service.ts
  Server/src/departments/dto/get-department.dto.ts
  Server/src/departments/entities/department.entity.ts
  Server/src/reservation/reservation.service.ts
  Server/src/semester/dto/create-semester.dto.ts
  Server/src/semester/dto/update-semester.dto.ts
  Server/src/semester/entities/semester.entity.ts
  Server/src/semester/semester.controller.spec.ts
  Server/src/semester/semester.controller.ts
  Server/src/semester/semester.module.ts
  Server/src/semester/semester.service.spec.ts
  Server/src/semester/semester.service.ts
  Server/src/users/dto/create-user.dto.ts
  Server/src/users/dto/login-user.dto.ts
  Server/src/users/entities/user.entity.ts
  Server/src/users/users.controller.ts
  Server/src/users/users.service.ts
Labels: BE, Feat, Fix, Refactor

#82 [ BE ] API 오류 해결/응답 클래스 수정
  Server/src/projects/dto/get-project.dto.ts
  Server/src/projects/entity/project.entity.ts
  Server/src/projects/projects.controller.ts
  Server/src/projects/projects.service.ts
  Server/src/studies/dto/get-study.dto.ts
  Server/src/studies/studies.controller.ts
  Server/src/studies/studies.service.ts
  Server/src/users/entities/user.entity.ts
Labels: BE, Fix, Refactor

#89 [ BE ] 동아리 관리 API 및 리팩토링
  Server/config/swagger.ts
  Server/src/app.module.ts
  Server/src/auths/auth.jwt.guard.ts
  Server/src/auths/auth.jwt.strategy.ts
  Server/src/auths/auth.service.ts
  Server/src/auths/roles.decorator.ts
  Server/src/auths/roles.guard.ts
  Server/src/club/club.controller.spec.ts
  Server/src/club/club.controller.ts
  Server/src/club/club.module.ts
  Server/src/club/club.service.spec.ts
  Server/src/club/club.service.ts
  Server/src/club/dto/create-club.dto.ts
  Server/src/club/dto/get-clubUser.dto.ts
  Server/src/club/dto/update-club.dto.ts
  Server/src/club/entities/club.entity.ts
  Server/src/semester/entities/semester.entity.ts
  Server/src/semester/semester.module.ts
  Server/src/users/dto/get-user.dto.ts
  Server/src/users/entities/user.entity.ts
  Server/src/users/users.controller.ts
  Server/src/users/users.service.ts
Labels: BE, Feat, Refactor

#94 [ BE ] 전체 스터디/프로젝트 조회 API 수정
  Server/src/projects/projects.service.ts
  Server/src/studies/studies.service.ts
Labels: BE, Fix

#98 [Feat] 어드민 페이지 라우터 수정 및 버그 수정
  .gitignore
  Client/src/API/Admin/index.ts
  Client/src/API/index.ts
  Client/src/Common/Constant/API.ts
  Client/src/Components/Molecules/Admin/SubSection/Member/index.tsx
  Client/src/Components/Molecules/Board/BoardPage/List/index.tsx
  Client/src/Components/Organisms/Main/BoardContent/index.tsx
  Client/src/Components/Organisms/Photos/List/index.tsx
  Client/src/Recoil/Admin/index.ts
  Client/src/Routes/AdminRoute.tsx
  Server/src/users/users.controller.ts
Labels: FE, Fix

#113 [ FE ] 멤버 가입 승인/거절 구현
  Client/src/API/Admin/index.ts
  Client/src/Common/Constant/API.ts
  Client/src/Common/Type/API.ts
  Client/src/Common/Type/Member/index.ts
  Client/src/Components/Molecules/Admin/MemberInfo/detail.tsx
  Client/src/Components/Molecules/Admin/SubSection/Member/MemberInfos.tsx
  Client/src/Components/Molecules/Admin/SubSection/Member/index.tsx
  Client/src/Components/Molecules/Admin/SubSection/MemberRegister/index.tsx
  Client/src/Components/Molecules/Admin/SubSection/MemberRegister/style.tsx
  Client/src/Components/Molecules/Admin/SubSection/MemberRegister/styles.tsx
  Client/src/Components/Molecules/Common/Modal/index.tsx
  Client/src/Recoil/Admin/index.ts
Labels: FE, Feat

#116 Fix : 유저 필터링 수정
  Client/src/Recoil/Admin/index.ts
Labels: Fix

#130 과방 대여 신청 내역 확인 모달창 작업, 스터디, 프로젝트 페이지 마감 콘텐츠의 신청 버튼 제거
  Client/src/Components/Molecules/Board/BoardPreview/Card/collecting.tsx
  Client/src/Components/Organisms/Reserve/ReserveCalendar/Body/index.tsx
  Client/src/Components/Organisms/Reserve/ReserveCalendar/Modal/index.tsx
  Client/src/Components/Organisms/Reserve/ReserveCalendar/Modal/styles.tsx
Labels: FE, Feat, Fix

#146 메인 페이지 게시판 제목 크기 반응형에 맞게 수정, 과방 대여 모달 창 반응형 레이아웃 구현
  Client/src/API/Account/index.ts
  Client/src/Components/Molecules/Content/ContentTitle/style.tsx
  Client/src/Components/Organisms/Reserve/ReserveCalendar/Modal/styles.tsx
Labels: FE, Feat, Fix, CSS

#154 [ BE ] 개발/배포 포트 env 수정
  Server/src/main.ts
Labels: BE, Fix

#164 [BE] 스터디 API 권한설정
  Server/package-lock.json
  Server/package.json
  Server/src/auths/auth.jwt.guard.ts
  Server/src/projects/projects.controller.ts
  Server/src/projects/projects.service.ts
  Server/src/studies/studies.controller.ts
  Server/src/studies/studies.service.ts
  Server/src/users/dto/get-userStudy.dto.ts
  Server/src/users/users.service.ts
Labels: BE, Feat, Fix

#165 [BE] 프로젝트 API 권한설정
  Server/src/projects/projects.controller.ts
  Server/src/projects/projects.service.ts
Labels: BE, Feat

#183 [BE] department DB변경, userID validation추가
  Server/src/auths/auth.service.ts
  Server/src/club/dto/get-clubUser.dto.ts
  Server/src/departments/entities/department.entity.ts
  Server/src/users/dto/create-user.dto.ts
  Server/src/users/dto/get-user.dto.ts
  Server/src/users/dto/login-user.dto.ts
  Server/src/users/entities/user.entity.ts
  Server/src/users/users.controller.ts
  Server/src/users/users.module.ts
  Server/src/users/users.service.ts
Labels: BE, Fix
