Repository AJOU-DEVELOPERS/Do-IT-Page, pull requests merged in 2022-02, with the labels that each got.

#5 Feat : Routing 처리 , API 에러처리 핸들링 , 함수 선언문 -> 함수 표현식
  Client/src/API/index.ts
  Client/src/App.tsx
  Client/src/Components/Pages/Admin.tsx
  Client/src/Components/Pages/Board.tsx
  Client/src/Components/Pages/Error.tsx
  Client/src/Components/Pages/Login.tsx
  Client/src/Components/Pages/Main.tsx
  Client/src/Components/Pages/MyPage.tsx
  Client/src/Hook/test/index.ts
  Client/src/Recoil/test/index.tsx
  Client/src/Routes/AdminRoute.tsx
  Client/src/Routes/PrivateRoute.tsx
  Client/tsconfig.paths.json
Labels: FE, Feat, Fix, Refactor

#8 Feat : 새로고침 및 페이지 전환간 로그인 체크 로직 생성
  Client/package-lock.json
  Client/package.json
  Client/public/checkLogIn.json
  Client/src/API/index.ts
  Client/src/API/test.ts
  Client/src/App.tsx
  Client/src/Common/Constant/index.ts
  Client/src/Components/Organisms/Header/index.tsx
  Client/src/Components/Organisms/Header/styles.tsx
  Client/src/Components/Pages/Admin.tsx
  Client/src/Components/Pages/Board.tsx
  Client/src/Components/Pages/Error.tsx
  Client/src/Components/Pages/Login.tsx
  Client/src/Components/Pages/Main.tsx
  Client/src/Components/Pages/MyPage.tsx
  Client/src/Hook/test/index.ts
  Client/src/Recoil/CheckLogin/index.tsx
  Client/src/Routes/AdminRoute.tsx
  Client/src/Routes/PrivateRoute.tsx
  Client/tsconfig.paths.json
Labels: FE, Feat, Fix, Refactor

#11 Fix : Code Review 이후 내용 수정
  Client/src/App.tsx
  Client/src/Common/Constant/index.ts
  Client/src/Components/Atoms/Button/index.tsx
  Client/src/Components/Atoms/Button/styles.tsx
Labels: FE, Fix, Refactor

#12 Feat : LoginPage -> Template -> Organism -> Molecules -> Atom
  Client/README.md
  Client/package-lock.json
  Client/package.json
  Client/public/checkLogIn.json
  Client/public/loginBg.jpeg
  Client/public/loginL.png
  Client/public/loginR.png
  Client/src/App.tsx
  Client/src/Common/Constant/index.ts
  Client/src/Common/Util/reset.ts
  Client/src/Components/Atoms/Button/index.tsx
  Client/src/Components/Atoms/Button/styles.tsx
  Client/src/Components/Atoms/Input/index.tsx
  Client/src/Components/Atoms/Input/styles.tsx
  Client/src/Components/Molecules/Login/Input.tsx
  Client/src/Components/Molecules/Login/index.tsx
  Client/src/Components/Molecules/Login/styles.tsx
  Client/src/Components/Organisms/Login/index.tsx
  Client/src/Components/Organisms/Login/styles.tsx
  Client/src/Components/Pages/Login.tsx
  Client/src/Components/Pages/index.tsx
  Client/src/Components/Templates/Login/index.tsx
  Client/src/Components/Templates/Login/styles.tsx
  Client/src/index.tsx
Labels: FE, Feat, CSS

#13 Feat : LoginPage -> Template -> Organism -> Molecules -> Atom
  Client/README.md
  Client/package-lock.json
  Client/package.json
  Client/public/checkLogIn.json
  Client/public/loginBg.jpeg
  Client/public/loginL.png
  Client/public/loginR.png
  Client/src/App.tsx
  Client/src/Common/Constant/index.ts
  Client/src/Common/Util/reset.ts
  Client/src/Components/Atoms/Button/index.tsx
  Client/src/Components/Atoms/Button/styles.tsx
  Client/src/Components/Atoms/Input/index.tsx
  Client/src/Components/Atoms/Input/styles.tsx
  Client/src/Components/Molecules/Login/Input.tsx
  Client/src/Components/Molecules/Login/index.tsx
  Client/src/Components/Molecules/Login/styles.tsx
  Client/src/Components/Organisms/Login/index.tsx
  Client/src/Components/Organisms/Login/styles.tsx
  Client/src/Components/Pages/Login.tsx
  Client/src/Components/Pages/index.tsx
  Client/src/Components/Templates/Login/index.tsx
  Client/src/Components/Templates/Login/styles.tsx
  Client/src/index.tsx
Labels: FE, Feat, CSS

#15 Feat : 메인 페이지, Carousel .
  Client/src/Common/Constant/index.ts
  Client/src/Common/Type/index.ts
  Client/src/Components/Atoms/Button/Login.tsx
  Client/src/Components/Atoms/Button/index.tsx
  Client/src/Components/Atoms/Button/styles.tsx
  Client/src/Components/Atoms/Input/index.tsx
  Client/src/Components/Atoms/Input/styles.tsx
  Client/src/Components/Molecules/Carousel/index.tsx
  Client/src/Components/Molecules/Carousel/styles.tsx
  Client/src/Components/Molecules/Login/Input.tsx
  Client/src/Components/Organisms/Header/index.tsx
  Client/src/Components/Organisms/Header/styles.tsx
  Client/src/Components/Organisms/Page/FirstContent/index.tsx
  Client/src/Components/Organisms/Page/FirstContent/styles.tsx
  Client/src/Components/Pages/index.tsx
  Client/src/Components/Templates/Page/index.tsx
Labels: FE, Feat, Fix, CSS

#18 Feat : Header , Basic Page ,
  Client/public/Logo.svg
  Client/public/carousel1.jpeg
  Client/public/carousel2.jpeg
  Client/public/process_logo.png
  Client/public/room_logo.png
  Client/public/secondContent.png
  Client/public/study_logo.png
  Client/public/user_icon.png
  Client/public/year.png
  Client/src/App.tsx
  Client/src/Common/Constant/index.ts
  Client/src/Common/Type/index.ts
  Client/src/Components/Atoms/Button/index.tsx
  Client/src/Components/Atoms/Button/styles.tsx
  Client/src/Components/Atoms/ContentImg/styles.tsx
  Client/src/Components/Atoms/Logo/index.tsx
  Client/src/Components/Atoms/Logo/styles.tsx
  Client/src/Components/Molecules/Carousel/index.tsx
  Client/src/Components/Molecules/Carousel/styles.tsx
  Client/src/Components/Molecules/Content/index.tsx
  Client/src/Components/Molecules/Content/styles.tsx
  Client/src/Components/Molecules/Header/index.tsx
  Client/src/Components/Molecules/Header/styles.tsx
  Client/src/Components/Organisms/Header/index.tsx
  Client/src/Components/Organisms/Header/styles.tsx
  Client/src/Components/Organisms/Page/Content/index.tsx
  Client/src/Components/Organisms/Page/Content/styles.tsx
  Client/src/Components/Organisms/Page/FirstContent/index.tsx
  Client/src/Components/Organisms/Page/FirstContent/styles.tsx
  Client/src/Components/Organisms/Page/Last/index.tsx
  Client/src/Components/Organisms/Page/Last/styles.tsx
  Client/src/Components/Organisms/Page/LastContent/index.tsx
  Client/src/Components/Organisms/Page/LastContent/styles.tsx
  Client/src/Components/Organisms/Page/MiddleContent/index.tsx
  Client/src/Components/Organisms/Page/MiddleContent/styles.tsx
  Client/src/Components/Templates/Login/styles.tsx
  Client/src/Components/Templates/Page/index.tsx
  Client/src/Components/Templates/Page/styles.tsx
Labels: FE, Feat, Fix, CSS

#22 [FE] 메인 페이지 UI 개발
  Client/package-lock.json
  Client/package.json
  Client/public/70205497.jfif
  Client/public/BaekJoonRanking.json
  Client/public/FreeBoardContent.json
  Client/public/NoticeBoardContent.json
  Client/public/PhotoBoardContent.json
  Client/public/ProjectBoardContent.json
  Client/public/RoomBoardContent.json
  Client/public/StudyBoardContent.json
  Client/public/bronze_icon.png
  Client/public/checkLogIn.json
  Client/public/gold_icon.png
  Client/public/silver_icon.png
  Client/src/API/index.ts
  Client/src/API/test.ts
  Client/src/Common/Constant/index.ts
  Client/src/Common/Style/index.ts
  Client/src/Common/Type/index.ts
  Client/src/Common/Util/index.ts
  Client/src/Components/Atoms/Logo/index.tsx
  Client/src/Components/Atoms/Logo/styles.tsx
  Client/src/Components/Molecules/BoardPreview/index.tsx
  Client/src/Components/Molecules/BoardPreview/style.tsx
  Client/src/Components/Molecules/CalendarDate/index.tsx
  Client/src/Components/Molecules/CalendarDate/style.tsx
  Client/src/Components/Molecules/ContentTitle/index.tsx
  Client/src/Components/Molecules/ContentTitle/style.tsx
  Client/src/Components/Molecules/Header/index.tsx
  Client/src/Components/Molecules/Header/style.tsx
  Client/src/Components/Molecules/Login/Input.tsx
  Client/src/Components/Molecules/PhotoCard/index.tsx
  Client/src/Components/Molecules/PhotoCard/style.tsx
  Client/src/Components/Molecules/RankingCard/index.tsx
  Client/src/Components/Molecules/RankingCard/style.tsx
  Client/src/Components/Organisms/Calendar/index.tsx
  Client/src/Components/Organisms/Calendar/style.tsx
  Client/src/Components/Organisms/Footer/index.tsx
  Client/src/Components/Organisms/Footer/style.tsx
  Client/src/Components/Organisms/Header/admin.tsx
  Client/src/Components/Organisms/Header/index.tsx
  Client/src/Components/Organisms/Main/BoardContent/index.tsx
  Client/src/Components/Organisms/Main/BoardContent/style.tsx
  Client/src/Components/Organisms/Main/NoticeContent/index.tsx
  Client/src/Components/Organisms/Main/NoticeContent/style.tsx
  Client/src/Components/Organisms/Main/PhotoContent/index.tsx
  Client/src/Components/Organisms/Main/PhotoContent/style.tsx
  Client/src/Components/Organisms/Main/RankingContent/index.tsx
  Client/src/Components/Organisms/Main/RankingContent/style.tsx
  Client/src/Components/Organisms/Page/Last/index.tsx
  Client/src/Components/Pages/Main.tsx
  Client/src/Components/Templates/Admin/index.tsx
  Client/src/Components/Templates/Main/index.tsx
  Client/src/Components/Templates/Main/style.tsx
  Client/src/Hook/test/index.ts
  Client/src/Recoil/BoardContent/index.ts
  Client/src/Recoil/NoticeContent/index.tsx
  Client/src/Routes/PublicRoute.tsx
  Client/tsconfig.paths.json
  README.md
Labels: FE, Feat, Refactor, CSS

#31 [ Feat ] 공지사항 게시판, 자유게시판 구현
  Client/public/dummyData/FreeBoardContent.json
  Client/public/dummyData/NoticeBoardContent.json
  Client/src/App.tsx
  Client/src/Common/Type/index.ts
  Client/src/Components/Molecules/BoardPage/Footer/index.tsx
  Client/src/Components/Molecules/BoardPage/Footer/styles.tsx
  Client/src/Components/Molecules/BoardPage/List/index.tsx
  Client/src/Components/Molecules/BoardPage/List/styles.tsx
  Client/src/Components/Molecules/BoardPreview/Basic/index.tsx
  Client/src/Components/Molecules/BoardPreview/Basic/style.tsx
  Client/src/Components/Molecules/BoardPreview/index.tsx
  Client/src/Components/Organisms/BoardBody/index.tsx
  Client/src/Components/Organisms/BoardBody/styles.tsx
  Client/src/Components/Pages/Board.tsx
  Client/src/Components/Pages/Notice.tsx
  Client/src/Components/Templates/Board/index.tsx
  Client/src/Components/Templates/Notice/index.tsx
  Client/src/Hook/test/index.ts
  Client/src/Recoil/BoardContent/index.ts
Labels: FE, Feat, Fix, CSS

#33 [ Fix ] 로그인 UI 수정
  Client/src/Common/Style/index.ts
  Client/src/Common/Type/index.ts
  Client/src/Components/Atoms/Button/Login.tsx
  Client/src/Components/Atoms/Button/index.tsx
  Client/src/Components/Atoms/Button/styles.tsx
  Client/src/Components/Atoms/Input/index.tsx
  Client/src/Components/Atoms/Input/styles.tsx
  Client/src/Components/Molecules/Account/LoginInput.tsx
  Client/src/Components/Molecules/Account/RegisterInput.tsx
  Client/src/Components/Molecules/Account/index.tsx
  Client/src/Components/Molecules/Account/styles.tsx
  Client/src/Components/Molecules/PostContent/index.tsx
  Client/src/Components/Molecules/PostContent/styles.tsx
  Client/src/Components/Molecules/Section/index.tsx
  Client/src/Components/Organisms/Account/styles.tsx
  Client/src/Components/Organisms/Admin/Section/styles.tsx
Labels: FE, Fix, Refactor, CSS

#32 [ Feat ] 로그인 후 메인 페이지 이벤트 작업
  Client/public/dummyData/FreeBoardContent.json
  Client/public/dummyData/NoticeBoardContent.json
  Client/public/dummyData/PhotoBoardContent.json
  Client/public/dummyData/RoomBoardContent.json
  Client/src/Common/Constant/index.ts
  Client/src/Common/Style/index.ts
  Client/src/Common/Type/index.ts
  Client/src/Common/Util/index.ts
  Client/src/Components/Molecules/BoardPreview/Card/index.tsx
  Client/src/Components/Molecules/BoardPreview/index.tsx
  Client/src/Components/Molecules/CalendarDate/style.tsx
  Client/src/Components/Molecules/ContentTitle/index.tsx
  Client/src/Components/Molecules/Header/Nav.tsx
  Client/src/Components/Molecules/RankingCard/style.tsx
  Client/src/Components/Organisms/Calendar/index.tsx
  Client/src/Components/Organisms/Main/BoardContent/index.tsx
  Client/src/Components/Organisms/Reserve/ReserveCalendar/Body/index.tsx
  Client/src/Components/Organisms/Reserve/ReserveCalendar/Header/index.tsx
  Client/src/Components/Organisms/Reserve/ReserveCalendar/index.tsx
  Client/src/Components/Templates/Main/index.tsx
  Client/src/Components/Templates/Main/style.tsx
  Client/src/Hook/test/index.ts
Labels: FE, Feat, Fix, Refactor, CSS

#38 [ Fix ] 스터디 페이지 UI 수정 및 컴포넌트 수정
  Client/public/dummyData/StudyBoardContent.json
  Client/src/Common/Constant/index.ts
  Client/src/Common/Type/index.ts
  Client/src/Components/Molecules/BoardPreview/Card/collecting.tsx
  Client/src/Components/Molecules/BoardPreview/Card/index.tsx
  Client/src/Components/Molecules/BoardPreview/Card/processing.tsx
  Client/src/Components/Molecules/BoardPreview/Card/style.tsx
  Client/src/Components/Molecules/BoardPreview/index.tsx
  Client/src/Components/Molecules/Postic/index.tsx
  Client/src/Components/Molecules/Postic/styles.tsx
  Client/src/Components/Organisms/Main/BoardContent/index.tsx
  Client/src/Components/Organisms/Study/index.tsx
  Client/src/Components/Organisms/Study/styles.tsx
  Client/src/Components/Templates/Study/index.tsx
  Client/src/Components/Templates/Study/styles.tsx
Labels: FE, Feat, Fix, Refactor, CSS

#41 [ Feat ] 프로젝트 UI 생성
  Client/src/Components/Molecules/Content/studyProject.tsx
  Client/src/Components/Molecules/Content/styles.tsx
  Client/src/Components/Pages/Project.tsx
  Client/src/Components/Templates/Project/index.tsx
  Client/src/Components/Templates/Project/styles.tsx
  Client/src/Components/Templates/Study/index.tsx
Labels: FE, Feat, CSS

#45 [Feat] API 작업
  Client/public/dummyData/reservation.json
  Client/public/dummyData/reservation/2022/2.json
  Client/src/API/Account/index.ts
  Client/src/API/Reservation/index.ts
  Client/src/API/index.ts
  Client/src/API/test.ts
  Client/src/Common/Constant/API.ts
  Client/src/Common/Constant/img.ts
  Client/src/Common/Constant/index.ts
  Client/src/Common/Style/index.ts
  Client/src/Common/Type/API.ts
  Client/src/Common/Type/Account/index.ts
  Client/src/Common/Type/Reservation/index.ts
  Client/src/Common/Util/index.ts
  Client/src/Components/Molecules/Account/LoginInput.tsx
  Client/src/Components/Molecules/Account/RegisterInput.tsx
  Client/src/Components/Molecules/Account/index.tsx
  Client/src/Components/Molecules/Account/styles.tsx
  Client/src/Components/Molecules/Account/util.ts
  Client/src/Components/Molecules/BoardPreview/Card/collecting.tsx
  Client/src/Components/Molecules/BoardPreview/Card/processing.tsx
  Client/src/Components/Molecules/Content/studyProject.tsx
  Client/src/Components/Molecules/RankingCard/index.tsx
  Client/src/Components/Organisms/Before/DoItCarousel/index.tsx
  Client/src/Components/Organisms/Before/DoItInfo/index.tsx
  Client/src/Components/Organisms/Before/DoItTodo/index.tsx
  Client/src/Components/Organisms/Calendar/index.tsx
  Client/src/Components/Organisms/Calendar/style.tsx
  Client/src/Components/Organisms/Main/BoardContent/style.tsx
  Client/src/Components/Organisms/Reserve/ReserveBox/index.tsx
  Client/src/Components/Organisms/Reserve/ReserveBox/util.ts
  Client/src/Components/Organisms/Reserve/ReserveCalendar/Body/index.tsx
  Client/src/Components/Organisms/Reserve/ReserveCalendar/Body/styles.tsx
  Client/src/Components/Organisms/Reserve/ReserveCalendar/Body/util.ts
  Client/src/Components/Organisms/Reserve/ReserveCalendar/Modal/index.tsx
  Client/src/Recoil/Reservation/index.tsx
Labels: FE, Feat, Fix, CSS
